# Uncomment the next line to define a global platform for your project
#  platform :ios, '8.0'


target 'Humantiv' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for Humantiv
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'


  target 'HumantivTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Humantiv-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Humantiv-tvOS

  target 'Humantiv-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
