# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'Humantiv' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'GoogleSignIn'
  # Pods for Humantiv
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'


# pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  target 'HumantivTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Humantiv-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Humantiv-tvOS

  target 'Humantiv-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
